-- procurement_specific_item_raw 테이블 컬럼에 한글 설명(COMMENT) 추가

USE g2b;

ALTER TABLE procurement_specific_item_raw
  MODIFY COLUMN procurement_method_type VARCHAR(64) DEFAULT NULL COMMENT '조달방식구분',
  MODIFY COLUMN contract_type VARCHAR(64) DEFAULT NULL COMMENT '계약유형',
  MODIFY COLUMN delivery_contract_type VARCHAR(64) DEFAULT NULL COMMENT '계약납품구분',
  MODIFY COLUMN reference_date VARCHAR(16) DEFAULT NULL COMMENT '기준일자',
  MODIFY COLUMN delivery_contract_no VARCHAR(64) NOT NULL COMMENT '계약납품통합번호',
  MODIFY COLUMN delivery_contract_change_seq INT NOT NULL COMMENT '계약납품통합변경차수',
  MODIFY COLUMN delivery_item_seq INT NOT NULL COMMENT '계약납품요구물품순번',
  MODIFY COLUMN is_final_delivery_request VARCHAR(8) DEFAULT NULL COMMENT '최종계약납품요구여부',
  MODIFY COLUMN demand_agency_no VARCHAR(64) DEFAULT NULL COMMENT '수요기관번호',
  MODIFY COLUMN demand_agency_name VARCHAR(255) DEFAULT NULL COMMENT '수요기관명',
  MODIFY COLUMN supervising_type VARCHAR(64) DEFAULT NULL COMMENT '소관구분',
  MODIFY COLUMN demand_agency_region VARCHAR(255) DEFAULT NULL COMMENT '수요기관지역',
  MODIFY COLUMN item_category_no VARCHAR(64) DEFAULT NULL COMMENT '물품분류번호',
  MODIFY COLUMN item_category_name VARCHAR(255) DEFAULT NULL COMMENT '물품분류명',
  MODIFY COLUMN detail_item_no VARCHAR(64) DEFAULT NULL COMMENT '세부품명번호',
  MODIFY COLUMN detail_item_name VARCHAR(255) DEFAULT NULL COMMENT '세부품명',
  MODIFY COLUMN item_identifier_no VARCHAR(64) DEFAULT NULL COMMENT '물품식별번호',
  MODIFY COLUMN item_identifier_name VARCHAR(255) DEFAULT NULL COMMENT '물품식별명',
  MODIFY COLUMN delivery_unit_name VARCHAR(255) DEFAULT NULL COMMENT '계약납품단위명',
  MODIFY COLUMN vendor_name VARCHAR(255) DEFAULT NULL COMMENT '업체',
  MODIFY COLUMN company_type_at_contract VARCHAR(64) DEFAULT NULL COMMENT '계약시점 기업형태구분',
  MODIFY COLUMN contract_title VARCHAR(500) DEFAULT NULL COMMENT '계약명',
  MODIFY COLUMN is_excellent_product VARCHAR(8) DEFAULT NULL COMMENT '우수제품여부',
  MODIFY COLUMN is_direct_purchase_target VARCHAR(8) DEFAULT NULL COMMENT '직접구매대상여부',
  MODIFY COLUMN is_mas VARCHAR(8) DEFAULT NULL COMMENT 'MAS여부',
  MODIFY COLUMN is_two_stage_proposal VARCHAR(8) DEFAULT NULL COMMENT '이단계경쟁제안서제출여부',
  MODIFY COLUMN first_reference_date VARCHAR(16) DEFAULT NULL COMMENT '최초기준일자',
  MODIFY COLUMN contract_no VARCHAR(64) DEFAULT NULL COMMENT '계약번호',
  MODIFY COLUMN contract_change_seq INT DEFAULT NULL COMMENT '계약변경차수',
  MODIFY COLUMN contract_method VARCHAR(128) DEFAULT NULL COMMENT '계약방법',
  MODIFY COLUMN delivery_place_name VARCHAR(500) DEFAULT NULL COMMENT '납품장소명',
  MODIFY COLUMN delivery_deadline_date VARCHAR(16) DEFAULT NULL COMMENT '납품기한일자',
  MODIFY COLUMN vendor_biz_reg_no VARCHAR(32) DEFAULT NULL COMMENT '업체사업자등록번호',
  MODIFY COLUMN delivery_terms VARCHAR(255) DEFAULT NULL COMMENT '인도조건',
  MODIFY COLUMN delivery_unit_price VARCHAR(64) DEFAULT NULL COMMENT '계약납품단가',
  MODIFY COLUMN delivery_quantity VARCHAR(64) DEFAULT NULL COMMENT '계약납품수량',
  MODIFY COLUMN supply_amount VARCHAR(64) DEFAULT NULL COMMENT '공급금액',
  MODIFY COLUMN delivery_quantity_delta VARCHAR(64) DEFAULT NULL COMMENT '계약납품증감수량',
  MODIFY COLUMN supply_amount_delta VARCHAR(64) DEFAULT NULL COMMENT '공급증감금액';
