-- procurement_raw 테이블 컬럼에 한글 설명(COMMENT) 추가 (물품 계약 상세내역 CSV 기준)

USE g2b;

ALTER TABLE procurement_raw
  MODIFY COLUMN procurement_type VARCHAR(50) DEFAULT NULL COMMENT '조달구분',
  MODIFY COLUMN contract_type VARCHAR(50) DEFAULT NULL COMMENT '계약구분',
  MODIFY COLUMN contract_no VARCHAR(100) NOT NULL COMMENT '계약번호',
  MODIFY COLUMN contract_change_seq BIGINT NOT NULL COMMENT '계약변경차수',
  MODIFY COLUMN item_seq BIGINT NOT NULL COMMENT '물품순번',
  MODIFY COLUMN is_final_contract VARCHAR(10) DEFAULT NULL COMMENT '최종계약여부',
  MODIFY COLUMN demand_agency_name TEXT COMMENT '수요기관명',
  MODIFY COLUMN demand_agency_code VARCHAR(50) DEFAULT NULL COMMENT '수요기관코드',
  MODIFY COLUMN demand_agency_type VARCHAR(50) DEFAULT NULL COMMENT '수요기관구분',
  MODIFY COLUMN demand_agency_region VARCHAR(100) DEFAULT NULL COMMENT '수요기관지역명',
  MODIFY COLUMN contract_title TEXT COMMENT '계약명',
  MODIFY COLUMN contract_law_type VARCHAR(100) DEFAULT NULL COMMENT '계약법유형',
  MODIFY COLUMN article_clause_name VARCHAR(200) DEFAULT NULL COMMENT '조항호명',
  MODIFY COLUMN contract_method VARCHAR(100) DEFAULT NULL COMMENT '계약방법명',
  MODIFY COLUMN item_category_no VARCHAR(20) DEFAULT NULL COMMENT '물품분류번호',
  MODIFY COLUMN item_category_name TEXT COMMENT '물품분류명',
  MODIFY COLUMN detail_item_no VARCHAR(50) DEFAULT NULL COMMENT '세부품명번호',
  MODIFY COLUMN detail_item_name TEXT COMMENT '세부품명',
  MODIFY COLUMN item_identifier_no VARCHAR(50) DEFAULT NULL COMMENT '물품식별번호',
  MODIFY COLUMN item_identifier_name TEXT COMMENT '물품식별명',
  MODIFY COLUMN is_mas VARCHAR(10) DEFAULT NULL COMMENT 'MAS여부',
  MODIFY COLUMN is_excellent_product VARCHAR(10) DEFAULT NULL COMMENT '우수제품여부',
  MODIFY COLUMN is_sme_competitive_item VARCHAR(10) DEFAULT NULL COMMENT '중기간경쟁물품여부',
  MODIFY COLUMN first_reference_date BIGINT DEFAULT NULL COMMENT '최초기준일자',
  MODIFY COLUMN reference_date BIGINT DEFAULT NULL COMMENT '기준일자',
  MODIFY COLUMN delivery_deadline VARCHAR(50) DEFAULT NULL COMMENT '납품기한',
  MODIFY COLUMN vendor_name TEXT COMMENT '업체명',
  MODIFY COLUMN vendor_biz_reg_no VARCHAR(50) DEFAULT NULL COMMENT '업체사업자등록번호',
  MODIFY COLUMN company_type VARCHAR(50) DEFAULT NULL COMMENT '기업구분',
  MODIFY COLUMN award_method VARCHAR(100) DEFAULT NULL COMMENT '낙찰결정방법',
  MODIFY COLUMN public_procurement_category_no VARCHAR(50) DEFAULT NULL COMMENT '공공조달분류번호',
  MODIFY COLUMN bid_notice_no VARCHAR(50) DEFAULT NULL COMMENT '입찰공고번호',
  MODIFY COLUMN bid_notice_seq BIGINT DEFAULT NULL COMMENT '입찰공고차수',
  MODIFY COLUMN long_term_contract_seq BIGINT DEFAULT NULL COMMENT '장기계약차수',
  MODIFY COLUMN is_long_term_continuous VARCHAR(10) DEFAULT NULL COMMENT '장기계속여부',
  MODIFY COLUMN unit VARCHAR(100) DEFAULT NULL COMMENT '단위',
  MODIFY COLUMN unit_price BIGINT DEFAULT NULL COMMENT '단가',
  MODIFY COLUMN quantity BIGINT DEFAULT NULL COMMENT '수량',
  MODIFY COLUMN quantity_delta BIGINT DEFAULT NULL COMMENT '증감수량',
  MODIFY COLUMN contract_amount BIGINT DEFAULT NULL COMMENT '계약금액',
  MODIFY COLUMN contract_amount_delta BIGINT DEFAULT NULL COMMENT '계약증감금액';
