-- 공사 계약 내역 CSV 적재용 테이블 (downloads_construction → construction_upload.py)

USE g2b;

CREATE TABLE IF NOT EXISTS construction_contract_raw (
  contract_no                      VARCHAR(100)  NOT NULL COMMENT '계약번호',
  contract_change_seq              BIGINT        NOT NULL COMMENT '계약변경차수',
  contract_date                    VARCHAR(20)   DEFAULT NULL COMMENT '계약일자',
  contract_title                   TEXT          DEFAULT NULL COMMENT '계약명',
  procurement_method_type          VARCHAR(50)   DEFAULT NULL COMMENT '조달방식구분',
  vendor_biz_reg_no                VARCHAR(50)   DEFAULT NULL COMMENT '업체사업자등록번호',
  vendor_name                      TEXT          DEFAULT NULL COMMENT '업체',
  demand_agency_code               VARCHAR(50)   DEFAULT NULL COMMENT '수요기관코드',
  demand_agency_name               TEXT          DEFAULT NULL COMMENT '수요기관명',
  site_region                      VARCHAR(100)  DEFAULT NULL COMMENT '현장지역',
  start_date                       VARCHAR(20)   DEFAULT NULL COMMENT '착수일자',
  completion_date                  VARCHAR(20)   DEFAULT NULL COMMENT '완수일자',
  total_completion_date             VARCHAR(20)   DEFAULT NULL COMMENT '총완수일자',
  business_type                    VARCHAR(100) DEFAULT NULL COMMENT '업종',
  contract_request_no              VARCHAR(100) DEFAULT NULL COMMENT '계약요청접수번호',
  initial_year_contract_no         VARCHAR(100) DEFAULT NULL COMMENT '초년도계약번호',
  long_term_continuation_seq       VARCHAR(20)  DEFAULT NULL COMMENT '장기계속차수',
  bid_notice_no                    VARCHAR(50)   DEFAULT NULL COMMENT '입찰공고번호',
  bid_notice_seq                   VARCHAR(20)  DEFAULT NULL COMMENT '입찰공고차수',
  award_rate                       VARCHAR(50)   DEFAULT NULL COMMENT '낙찰율',
  first_contract_date              VARCHAR(20)   DEFAULT NULL COMMENT '최초계약일자',
  is_first_contract                VARCHAR(10)  DEFAULT NULL COMMENT '최초계약여부',
  is_final_contract                 VARCHAR(10)  DEFAULT NULL COMMENT '최종계약여부',
  is_initial_long_term_contract    VARCHAR(10)  DEFAULT NULL COMMENT '최초장기계속계약여부',
  department_type                  VARCHAR(50)  DEFAULT NULL COMMENT '소관구분',
  demand_agency_region             VARCHAR(100) DEFAULT NULL COMMENT '수요기관지역',
  is_women_enterprise_at_contract  VARCHAR(10)  DEFAULT NULL COMMENT '계약시점 여성기업인증여부',
  company_type_at_contract         VARCHAR(50)  DEFAULT NULL COMMENT '계약시점 기업형태구분',
  contract_law_type                 VARCHAR(100) DEFAULT NULL COMMENT '계약법유형',
  standard_contract_method         VARCHAR(100) DEFAULT NULL COMMENT '표준계약방법',
  joint_supply_type                VARCHAR(100) DEFAULT NULL COMMENT '공동수급구성방식',
  contract_branch                   VARCHAR(100) DEFAULT NULL COMMENT '계약지청',
  contract_agency_name             TEXT          DEFAULT NULL COMMENT '계약기관명',
  bid_contract_method              VARCHAR(100) DEFAULT NULL COMMENT '입찰계약방법',
  award_method                     VARCHAR(100) DEFAULT NULL COMMENT '낙찰방법',
  public_procurement_category_major VARCHAR(50) DEFAULT NULL COMMENT '대분류공공조달분류',
  public_procurement_category_mid  VARCHAR(50)  DEFAULT NULL COMMENT '중분류공공조달분류',
  public_procurement_category_name TEXT          DEFAULT NULL COMMENT '공공조달분류명',
  contract_amount                  BIGINT        DEFAULT NULL COMMENT '계약금액',
  contract_amount_delta            BIGINT        DEFAULT NULL COMMENT '계약증감금액',
  first_contract_amount            BIGINT        DEFAULT NULL COMMENT '최초계약금액',
  total_supplementary_amount      BIGINT        DEFAULT NULL COMMENT '총부기계약금액',
  estimated_price                  BIGINT        DEFAULT NULL COMMENT '예정가격',
  estimated_amount                BIGINT        DEFAULT NULL COMMENT '추정금액',
  award_amount                     BIGINT        DEFAULT NULL COMMENT '낙찰금액',
  PRIMARY KEY (contract_no, contract_change_seq),
  KEY idx_vendor_biz_reg_no (vendor_biz_reg_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='공사 계약 내역 CSV 적재 (2017~2025 등)';
